### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zonphyozaw** [aungkyawkyawsoe/project-test#2]
# Need to update 
- Update README.md file
- [x] @aungkyawkyawsoe 
- [x] @zonphyozaw

**Comment by aungkyawkyawsoe** [comment]
Why you need this feature @zonphyozaw

**Comment by zonphyozaw** [comment]
> Why you need this feature @zonphyozaw

I need to edit this project

**Comment by aungkyawkyawsoe** [comment]
> > Why you need this feature @zonphyozaw
> 
> I need to edit this project

OK! I'll add it.
